name: wallet
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5

  # Storage
  shared_preferences: 2.2.2
  flutter_secure_storage: 10.0.0

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: 2.1.2

  # UI
  flutter_animate: 4.5.0
  fl_chart: 1.1.1
  google_fonts: 8.0.1
  flutter_svg: 2.0.10+1
  intl: 0.20.2
  cupertino_icons: 1.0.8
  
  # Theming & Icons (Paisa Replica)
  flex_color_picker: ^3.4.1
  material_symbols_icons: ^4.27.6
  dynamic_color: ^1.7.0

  # File / Permissions
  csv: 6.0.0
  permission_handler: 12.0.1
  open_filex: ^4.4.0
  flutter_markdown: ^0.7.1
  url_launcher: ^6.2.6
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.1

  flutter_lints: 4.0.0
  flutter_launcher_icons: ^0.14.4

  # Code Generation
  build_runner: 2.4.13
  isar_generator:
    path: isar_community/packages/isar_generator
  riverpod_generator: 2.4.0

# dependency_overrides:
 
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans/Product Sans Regular.ttf
        - asset: assets/fonts/ProductSans/Product Sans Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans/Product Sans Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans/Product Sans Bold Italic.ttf
          weight: 700
          style: italic

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPro/SFUIDisplay-Regular.otf
        - asset: assets/fonts/SFPro/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFPro/SFUIDisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFPro/SFUIDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFPro/SFUIDisplay-Thin.otf
          weight: 100
        - asset: assets/fonts/SFPro/SFUIDisplay-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SFPro/SFUIDisplay-Heavy.otf
          weight: 800
        - asset: assets/fonts/SFPro/SFUIDisplay-Black.otf
          weight: 900

    - family: AppleColorEmoji
      fonts:
        - asset: assets/fonts/Emoji/iOS15.4_Fixed_space.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ColourTransparent.svg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/ColourTransparent.svg"
  adaptive_icon_monochrome: "assets/icon/Themed.svg"
